### PR TITLE
Logrotate configuration

### PR DESCRIPTION
**Pull request by madAndroid**
### Description of the Change

In order to ensure that FluentD implements it's own logrotate mechanism, I'd like to be able to configure this in the systemd unit file

### Benefits

The disks on an instance provisioned by the module will not fill up.

### Possible Drawbacks

Logs will be rotated on instances which already have FluentD configured

### CODE REVIEW

**Comment by madAndroid** [comment]
Not sure why the tests are failing, the daemon starts fine with the config in our dev environment:
```
$ ps auxf | grep fluentd
andrew.+ 16126  0.0  0.0  12784   996 pts/0    S+   05:59   0:00              \_ grep fluentd
fluentd  15466  0.0  1.4 277808 29964 ?        Sl   05:47   0:00 /usr/bin/ruby2.3 /usr/local/bin/fluentd -d /run/fluentd/fluentd.pid -c /etc/fluent/fluent.conf -o /var/log/fluent/fluent.log --log-rotate-age daily
fluentd  15471 18.8  9.6 957960 196892 ?       Sl   05:47   2:12  \_ /usr/bin/ruby2.3 -Eascii-8bit:ascii-8bit /usr/local/bin/fluentd -d /run/fluentd/fluentd.pid -c /etc/fluent/fluent.conf -o /var/log/fluent/fluent.log --log-rotate-age daily --under-supervisor
```

**Comment by jnogol** [comment]
Probably failed because of some Travis weird stuff. Let me clone your repo and check it out.

**Comment by madAndroid** [comment]
Awesome, thanks :)

**Comment by jnogol** [comment]
I figured this out. Yes, tests are failing, but because the default version for our role is 0.12.40 and I guess you're using 1.x and the option you provided wasn't in that version. We're gonna open an issue to update our default version soon.

In any case, a couple of things:

- In the scenario that someone doesn't want to use Fluentd log rotation (using instead Logrotate, for instance) is not available using your suggestion.
- We would prefer to use a list and render it in the template for the service file, like in this role: https://github.com/idealista/prometheus_server-role/blob/master/defaults/main.yml#L64. Could you please commit this?
- Anyway, when updating the default Fluent version, I will add support for providing templates via playbook, like in our Prometheus Role: https://github.com/idealista/prometheus_server-role/blob/master/defaults/main.yml#L36, https://github.com/idealista/prometheus_server-role/blob/master/tasks/install.yml#L85, in case you want to wait for it (can't say exactly when this feature will be released).

**Comment by jnogol** [comment]
I've submitted a PR that could be interesting. Feel free to provide us with feedback :)

https://github.com/idealista/fluentd-role/pull/15

**Comment by madAndroid** [comment]
Apologies for not responding sooner - very short of time atm :(
This _does_ look interesting .. will take a look and see if I can implement this in our infra ... thanks for this!

**Comment by jnogol** [comment]
Hi @madAndroid, I'm closing the PR as I guess the problem is solved now. If it is not, feel free to reopen the PR. Thanks again for your contribution

**Pull request closed without merging**
